version: '3.8'

services:
  pptpd:
    build:
      context: .
      dockerfile: Dockerfile
    image: pptp-docker
    container_name: pptpd
    hostname: pptpd
    volumes:
      - ./data/pptpd.conf:/etc/pptpd.conf
      - ./data/pptpd-options:/etc/ppp/pptpd-options
      - ./data/chap-secrets:/etc/ppp/chap-secrets
    privileged: true
    restart: always
#    ports:
#      - 1723:1723
    network_mode: host
